### ISSUE TITLE
Input of activity is not shown

### ISSUE THREAD

**Issue by jarvan-jiang** [microsoft/DurableFunctionsMonitor#216]
Hello,

I have been using the docker version(v6.5) for MSSQL storage provider through this [document ](https://github.com/microsoft/DurableFunctionsMonitor/tree/main/custom-backends/mssql#how-to-run-as-a-docker-container).

Everything works perfectly except the input of activity is not shown, I checked the response is always null, meanwhile in DB it is correct stored.

I tried the locally running, and it has same issue.

**Comment by scale-tone** [comment]
@jarvan-jiang , can I ask you to try [this fix](https://github.com/microsoft/DurableFunctionsMonitor/commit/a8ebabd950947c46f412c985908752955381d830) locally, to see if it works for you?

**Comment by jarvan-jiang** [comment]
> [@jarvan-jiang](https://github.com/jarvan-jiang) , can I ask you to try [this fix](https://github.com/microsoft/DurableFunctionsMonitor/commit/a8ebabd950947c46f412c985908752955381d830) locally, to see if it works for you?

I tried local version, works fine!

**Comment by scale-tone** [comment]
Should be fixed as part of [v6.6](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.6).

**Comment by jarvan-jiang** [comment]
Hi @scale-tone , I have upgraded to v6.6 but still not working.
I checked git and downloaded source code neither them include change from Program.cs , could you double check that or am I missing something?

**Comment by scale-tone** [comment]
Sorry, my fault, I must have forgotten to merge my changes into main.
Just did that and re-pushed the docker images.
Please, try again.

**Comment by jarvan-jiang** [comment]
It's working fine now in docker version. Thank you!
